### PR TITLE
Add example of getting battery information

### PR DESCRIPTION
**Pull request by timsneath**
## Description

Adds a couple of battery-related classes that enable reporting on available power. Adds an example of calling them. 

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by halildurmus** [comment]
Awesome, thank you!

**Comment by timsneath** [comment]
Yay! My first commit :) Thanks for the reminder about `README.md`. 

Do you want to require review approvals on this repo? I'm sure others will follow in my footsteps.

**Comment by halildurmus** [comment]
Yes, definitely :)

**Comment by halildurmus** [comment]
In case you haven't noticed yet, there is a new tool called [add_type](https://github.com/dart-windows/dartwinrt/blob/main/tool/README.md#add-new-winrt-apis) located in the `tool\` directory.

This tool simplifies the process of adding new WinRT types by analyzing the type and identifying any dependent types (if any), which it then adds to JSON files. The tool also fetches relevant documentation for the types from Microsoft's website, which is great.

Just wanted to let you know as manually adding a new WinRT class with extensive dependent types can be a cumbersome task (e.g. `StorageFile`).

**Comment by timsneath** [comment]
Yup! That worked a treat for me 🎉 

(I did try it with Windows.ApplicationModel.DataTransfer.Clipboard, and that was less successful, because missing support for map projections. But that's fine -- I'll keep exploring interesting APIs as I have time.)

**Pull request merged**
